### PR TITLE
Adding flags for more customable parameter.

### PR DESCRIPTION
**Pull request by NTT1906**
Hello, I made some changes to the code so that it can construct type 1 parameters, which you can test with your test plugin by typing "/test [player] <t:e:s:t>". I also changed some other things to make the code easier to read and edit (mostly for shorting it).

### CODE REVIEW

**Comment by NTT1906** [comment]
Can I have any of your contact media?

**Comment by sky-min** [comment]
> 연락 가능한 매체가 있습니까?
https://t.me/skymin468

I'm sorry to check now.

**Comment by NTT1906** [comment]
> > 연락 가능한 매체가 있습니까?
> > https://t.me/skymin468
> 
> I'm sorry to check now.

i can't send you messages, it seems like either you or the app blocked me :c

**Comment by sky-min** [comment]
> > > 작동하지 않는 매체? 
> > > https://t.me/skymin468
> > 
> > 
> > 지금 확인해서 죄송합니다.
> 
> 당신에게 메시지를 보낼 수 없습니다. 당신이나 앱이 저를 차단한 것 같습니다 :c

discord: skymin#1409

**Pull request merged**
